import type { Restaurant, MenuItem, MenuCategory, Order, Review, Category, UserProfile } from '@/types';

export const CATEGORIES: Category[] = [
  { id: 'all', name: 'All', icon: 'grid-outline', color: '#FF6B35' },
  { id: 'pizza', name: 'Pizza', icon: 'pizza-outline', color: '#E74C3C' },
  { id: 'burgers', name: 'Burgers', icon: 'fast-food-outline', color: '#E67E22' },
  { id: 'sushi', name: 'Sushi', icon: 'fish-outline', color: '#3498DB' },
  { id: 'desserts', name: 'Desserts', icon: 'ice-cream-outline', color: '#9B59B6' },
  { id: 'healthy', name: 'Healthy', icon: 'leaf-outline', color: '#27AE60' },
  { id: 'pasta', name: 'Pasta', icon: 'restaurant-outline', color: '#F39C12' },
  { id: 'tacos', name: 'Tacos', icon: 'flame-outline', color: '#E74C3C' },
];

export const RESTAURANTS: Restaurant[] = [
  {
    id: 'r1',
    name: 'Napoli Fire',
    cuisine: ['Italian', 'Pizza'],
    imageUrl: 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
    rating: 4.8,
    reviewCount: 1240,
    deliveryTime: '20–30 min',
    deliveryFee: 1.99,
    minOrder: 15,
    distance: '1.2 km',
    isOpen: true,
    isFeatured: true,
    tags: ['Wood-fired', 'Authentic', 'Popular'],
    address: '42 Margherita Lane, Downtown',
    description: 'Authentic Neapolitan pizza baked in a 900°F wood-fired oven. Every pie is crafted with imported San Marzano tomatoes and fresh buffalo mozzarella.',
  },
  {
    id: 'r2',
    name: 'Stack & Smash',
    cuisine: ['American', 'Burgers'],
    imageUrl: 'https://images.pexels.com/photos/1633578/pexels-photo-1633578.jpeg',
    rating: 4.7,
    reviewCount: 893,
    deliveryTime: '15–25 min',
    deliveryFee: 0.99,
    minOrder: 12,
    distance: '0.8 km',
    isOpen: true,
    isFeatured: true,
    tags: ['Smash Burgers', 'Craft Beer', 'Late Night'],
    address: '18 Griddle Street, West End',
    description: 'Double-smashed patties, melty American cheese, and our legendary special sauce. Burgers the way they were meant to be — messy and delicious.',
  },
  {
    id: 'r3',
    name: 'Sakura Garden',
    cuisine: ['Japanese', 'Sushi'],
    imageUrl: 'https://images.pexels.com/photos/2098085/pexels-photo-2098085.jpeg',
    rating: 4.9,
    reviewCount: 2105,
    deliveryTime: '30–45 min',
    deliveryFee: 2.99,
    minOrder: 25,
    distance: '2.1 km',
    isOpen: true,
    isFeatured: true,
    tags: ['Premium', 'Omakase', 'Fresh Daily'],
    address: '7 Cherry Blossom Ave, Eastside',
    description: 'Master chef Kenji brings two decades of Tokyo sushi experience to your doorstep. Premium-grade fish sourced daily from Tsukiji market.',
  },
  {
    id: 'r4',
    name: 'Green Bowl Co.',
    cuisine: ['Healthy', 'Bowls'],
    imageUrl: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
    rating: 4.6,
    reviewCount: 678,
    deliveryTime: '20–35 min',
    deliveryFee: 1.49,
    minOrder: 14,
    distance: '1.5 km',
    isOpen: true,
    isFeatured: false,
    tags: ['Vegan Options', 'Organic', 'Gluten-Free'],
    address: '33 Wellness Way, Midtown',
    description: 'Nutrient-packed bowls built around locally sourced greens, ancient grains, and house-made dressings. Eat well, feel better.',
  },
  {
    id: 'r5',
    name: 'La Trattoria',
    cuisine: ['Italian', 'Pasta'],
    imageUrl: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg',
    rating: 4.5,
    reviewCount: 1432,
    deliveryTime: '25–40 min',
    deliveryFee: 2.49,
    minOrder: 20,
    distance: '1.9 km',
    isOpen: true,
    isFeatured: false,
    tags: ['Homemade Pasta', 'Family Recipe', 'Wine Pairing'],
    address: '55 Via Roma, Little Italy',
    description: 'Three generations of Rossi family recipes made fresh every morning. Our pasta is hand-rolled daily and our sauces slow-cooked for six hours.',
  },
  {
    id: 'r6',
    name: 'Taco Loco',
    cuisine: ['Mexican', 'Tacos'],
    imageUrl: 'https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg',
    rating: 4.4,
    reviewCount: 521,
    deliveryTime: '15–25 min',
    deliveryFee: 0.99,
    minOrder: 10,
    distance: '0.6 km',
    isOpen: true,
    isFeatured: false,
    tags: ['Street Style', 'Spicy Options', 'Fast'],
    address: '9 Fiesta Boulevard, South Quarter',
    description: 'Straight-up street tacos with authentic Mexico City flavors. Al pastor off the trompo, hand-pressed corn tortillas, and salsas ground fresh daily.',
  },
  {
    id: 'r7',
    name: 'Cloud Nine Desserts',
    cuisine: ['Desserts', 'Bakery'],
    imageUrl: 'https://images.pexels.com/photos/1126359/pexels-photo-1126359.jpeg',
    rating: 4.7,
    reviewCount: 345,
    deliveryTime: '20–30 min',
    deliveryFee: 1.99,
    minOrder: 18,
    distance: '1.1 km',
    isOpen: true,
    isFeatured: true,
    tags: ['Artisan', 'Seasonal', 'Award Winning'],
    address: '12 Sugar Street, Arts District',
    description: 'Pastry chef Marie creates show-stopping desserts that are almost too beautiful to eat. Almost. Each creation is a small work of art.',
  },
  {
    id: 'r8',
    name: 'Seoul Kitchen',
    cuisine: ['Korean', 'BBQ'],
    imageUrl: 'https://images.pexels.com/photos/2673353/pexels-photo-2673353.jpeg',
    rating: 4.6,
    reviewCount: 789,
    deliveryTime: '25–40 min',
    deliveryFee: 2.49,
    minOrder: 20,
    distance: '2.4 km',
    isOpen: false,
    isFeatured: false,
    tags: ['Korean BBQ', 'Banchan', 'Kimchi'],
    address: '88 Hangang Road, Koreatown',
    description: 'Bringing the authentic tastes of Seoul to your home. Marinated meats, house-made kimchi, and twelve rotating banchan side dishes.',
  },
];

export const MENU_CATEGORIES: MenuCategory[] = [
  { id: 'starters', name: 'Starters' },
  { id: 'mains', name: 'Mains' },
  { id: 'drinks', name: 'Drinks' },
  { id: 'desserts', name: 'Desserts' },
];

export const MENU_ITEMS: MenuItem[] = [
  // Napoli Fire (r1)
  { id: 'm1', restaurantId: 'r1', categoryId: 'starters', name: 'Bruschetta al Pomodoro', description: 'Toasted sourdough, heirloom tomatoes, fresh basil, extra virgin olive oil', price: 9.50, imageUrl: 'https://images.pexels.com/photos/1437267/pexels-photo-1437267.jpeg', isPopular: true, isVegetarian: true, calories: 280 },
  { id: 'm2', restaurantId: 'r1', categoryId: 'starters', name: 'Burrata Caprese', description: 'Creamy burrata, San Marzano tomatoes, Sicilian sea salt, aged balsamic', price: 14.00, imageUrl: 'https://images.pexels.com/photos/4518843/pexels-photo-4518843.jpeg', isPopular: true, isVegetarian: true, calories: 340 },
  { id: 'm3', restaurantId: 'r1', categoryId: 'mains', name: 'Margherita Classica', description: 'San Marzano tomato, fior di latte, fresh basil, extra virgin olive oil', price: 18.00, imageUrl: 'https://images.pexels.com/photos/825661/pexels-photo-825661.jpeg', isPopular: true, isVegetarian: true, calories: 820 },
  { id: 'm4', restaurantId: 'r1', categoryId: 'mains', name: 'Diavola Picante', description: 'Spicy Calabrian nduja, smoked provola, charred cherry tomatoes, chili flakes', price: 22.00, imageUrl: 'https://images.pexels.com/photos/1566837/pexels-photo-1566837.jpeg', isPopular: false, isVegetarian: false, calories: 950 },
  { id: 'm5', restaurantId: 'r1', categoryId: 'mains', name: 'Quattro Formaggi', description: 'Mozzarella, gorgonzola, parmigiano reggiano, pecorino, honey drizzle', price: 21.00, imageUrl: 'https://images.pexels.com/photos/2714722/pexels-photo-2714722.jpeg', isPopular: true, isVegetarian: true, calories: 1020 },
  { id: 'm6', restaurantId: 'r1', categoryId: 'drinks', name: 'San Pellegrino', description: 'Italian sparkling mineral water 500ml', price: 3.50, imageUrl: 'https://images.pexels.com/photos/3407777/pexels-photo-3407777.jpeg', isPopular: false, isVegetarian: true, calories: 0 },
  { id: 'm7', restaurantId: 'r1', categoryId: 'desserts', name: 'Tiramisu della Casa', description: 'Savoiardi biscuits, mascarpone cream, espresso, a dusting of dark cocoa', price: 9.00, imageUrl: 'https://images.pexels.com/photos/6880219/pexels-photo-6880219.jpeg', isPopular: true, isVegetarian: true, calories: 450 },

  // Stack & Smash (r2)
  { id: 'm8', restaurantId: 'r2', categoryId: 'starters', name: 'Crispy Onion Rings', description: 'Beer-battered rings with chipotle mayo dip', price: 7.50, imageUrl: 'https://images.pexels.com/photos/1893555/pexels-photo-1893555.jpeg', isPopular: true, isVegetarian: true, calories: 480 },
  { id: 'm9', restaurantId: 'r2', categoryId: 'starters', name: 'Loaded Fries', description: 'Crinkle fries, pulled pork, cheddar sauce, jalapeños, sour cream', price: 11.00, imageUrl: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg', isPopular: true, isVegetarian: false, calories: 720 },
  { id: 'm10', restaurantId: 'r2', categoryId: 'mains', name: 'The Classic Smash', description: 'Double smash patty, American cheese, pickles, onion, special sauce, brioche bun', price: 15.50, imageUrl: 'https://images.pexels.com/photos/1639565/pexels-photo-1639565.jpeg', isPopular: true, isVegetarian: false, calories: 890 },
  { id: 'm11', restaurantId: 'r2', categoryId: 'mains', name: 'Mushroom Swiss Melt', description: 'Beef patty, sautéed wild mushrooms, gruyère, truffle aioli, pretzel bun', price: 17.50, imageUrl: 'https://images.pexels.com/photos/3616956/pexels-photo-3616956.jpeg', isPopular: false, isVegetarian: false, calories: 820 },
  { id: 'm12', restaurantId: 'r2', categoryId: 'mains', name: 'Spicy Habanero', description: 'Beef patty, habanero jam, pepper jack, crispy fried onions, lettuce', price: 16.00, imageUrl: 'https://images.pexels.com/photos/2983101/pexels-photo-2983101.jpeg', isPopular: true, isVegetarian: false, calories: 910 },
  { id: 'm13', restaurantId: 'r2', categoryId: 'drinks', name: 'Craft Milkshake', description: 'Thick shake in vanilla, chocolate, or strawberry — your choice', price: 8.50, imageUrl: 'https://images.pexels.com/photos/3727250/pexels-photo-3727250.jpeg', isPopular: true, isVegetarian: true, calories: 680 },

  // Sakura Garden (r3)
  { id: 'm14', restaurantId: 'r3', categoryId: 'starters', name: 'Edamame Shio', description: 'Steamed soybeans seasoned with flake salt and sesame oil', price: 6.00, imageUrl: 'https://images.pexels.com/photos/3650436/pexels-photo-3650436.jpeg', isPopular: false, isVegetarian: true, calories: 180 },
  { id: 'm15', restaurantId: 'r3', categoryId: 'starters', name: 'Gyoza (6pc)', description: 'Pan-fried pork and cabbage dumplings, yuzu ponzu dipping sauce', price: 10.50, imageUrl: 'https://images.pexels.com/photos/5409020/pexels-photo-5409020.jpeg', isPopular: true, isVegetarian: false, calories: 320 },
  { id: 'm16', restaurantId: 'r3', categoryId: 'mains', name: 'Omakase Nigiri Set (10pc)', description: 'Chef\'s selection of premium nigiri — bluefin tuna, salmon, scallop, and more', price: 52.00, imageUrl: 'https://images.pexels.com/photos/2098085/pexels-photo-2098085.jpeg', isPopular: true, isVegetarian: false, calories: 560 },
  { id: 'm17', restaurantId: 'r3', categoryId: 'mains', name: 'Dragon Roll (8pc)', description: 'Shrimp tempura inside, avocado on top, tobiko, eel sauce', price: 24.00, imageUrl: 'https://images.pexels.com/photos/1148086/pexels-photo-1148086.jpeg', isPopular: true, isVegetarian: false, calories: 480 },
  { id: 'm18', restaurantId: 'r3', categoryId: 'desserts', name: 'Mochi Ice Cream (3pc)', description: 'Handmade mochi with matcha, black sesame, and mango ice cream', price: 10.00, imageUrl: 'https://images.pexels.com/photos/3625372/pexels-photo-3625372.jpeg', isPopular: true, isVegetarian: true, calories: 360 },
];

export const REVIEWS: Review[] = [
  {
    id: 'rev1',
    restaurantId: 'r1',
    userName: 'Alessandro M.',
    userAvatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg',
    rating: 5,
    comment: 'Best pizza outside of Naples. The dough is perfectly charred and the San Marzano sauce is divine. Worth every penny!',
    date: '2 days ago',
    helpful: 24,
  },
  {
    id: 'rev2',
    restaurantId: 'r1',
    userName: 'Sophie W.',
    userAvatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg',
    rating: 4,
    comment: 'Incredible flavors, arrived piping hot. The Diavola is genuinely spicy — love it. Only wish delivery was a bit faster.',
    date: '5 days ago',
    helpful: 17,
  },
  {
    id: 'rev3',
    restaurantId: 'r2',
    userName: 'Marcus L.',
    userAvatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg',
    rating: 5,
    comment: 'The Classic Smash is life-changing. Perfectly seasoned, beautiful char, and the sauce is addictive. Already ordered three times this week.',
    date: '1 day ago',
    helpful: 31,
  },
];

export const PAST_ORDERS: Order[] = [
  {
    id: 'ord1',
    restaurantName: 'Napoli Fire',
    restaurantImageUrl: 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
    items: [
      { name: 'Margherita Classica', quantity: 2, price: 18.00 },
      { name: 'Burrata Caprese', quantity: 1, price: 14.00 },
    ],
    status: 'delivered',
    totalAmount: 53.97,
    deliveryFee: 1.99,
    placedAt: '2024-01-15T19:30:00Z',
    estimatedDelivery: '2024-01-15T20:00:00Z',
    address: '14 Maple Street, Apt 3B',
  },
  {
    id: 'ord2',
    restaurantName: 'Stack & Smash',
    restaurantImageUrl: 'https://images.pexels.com/photos/1633578/pexels-photo-1633578.jpeg',
    items: [
      { name: 'The Classic Smash', quantity: 1, price: 15.50 },
      { name: 'Loaded Fries', quantity: 1, price: 11.00 },
      { name: 'Craft Milkshake', quantity: 2, price: 8.50 },
    ],
    status: 'delivered',
    totalAmount: 45.49,
    deliveryFee: 0.99,
    placedAt: '2024-01-12T12:15:00Z',
    estimatedDelivery: '2024-01-12T12:45:00Z',
    address: '14 Maple Street, Apt 3B',
  },
  {
    id: 'ord3',
    restaurantName: 'Sakura Garden',
    restaurantImageUrl: 'https://images.pexels.com/photos/2098085/pexels-photo-2098085.jpeg',
    items: [
      { name: 'Omakase Nigiri Set (10pc)', quantity: 1, price: 52.00 },
      { name: 'Dragon Roll (8pc)', quantity: 1, price: 24.00 },
      { name: 'Mochi Ice Cream (3pc)', quantity: 1, price: 10.00 },
    ],
    status: 'delivered',
    totalAmount: 91.98,
    deliveryFee: 2.99,
    placedAt: '2024-01-08T20:00:00Z',
    estimatedDelivery: '2024-01-08T20:45:00Z',
    address: '14 Maple Street, Apt 3B',
  },
];

export const ACTIVE_ORDER: Order = {
  id: 'ord4',
  restaurantName: 'Stack & Smash',
  restaurantImageUrl: 'https://images.pexels.com/photos/1633578/pexels-photo-1633578.jpeg',
  items: [
    { name: 'The Classic Smash', quantity: 2, price: 15.50 },
    { name: 'Crispy Onion Rings', quantity: 1, price: 7.50 },
  ],
  status: 'preparing',
  totalAmount: 40.97,
  deliveryFee: 0.99,
  placedAt: '2024-01-16T18:45:00Z',
  estimatedDelivery: '2024-01-16T19:15:00Z',
  address: '14 Maple Street, Apt 3B',
};

export const MOCK_USER: UserProfile = {
  id: 'u1',
  name: 'Jordan Rivera',
  email: 'jordan.rivera@example.com',
  phone: '+1 (555) 012-3456',
  avatarUrl: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg',
  totalOrders: 47,
  totalReviews: 12,
  savedRestaurants: 8,
  addresses: [
    { id: 'a1', label: 'Home', fullAddress: '14 Maple Street, Apt 3B, New York, NY 10001', isDefault: true },
    { id: 'a2', label: 'Work', fullAddress: '250 West 39th Street, Floor 12, New York, NY 10018', isDefault: false },
  ],
};
